<?php

/**
 * @file
 * Contains article.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function article_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the article module.
    case 'help.page.article':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Article module') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function article_theme() {
  
  return array(
    'article' => array(
      'variables' => array( 'items' => array(), 'title' => '')
    )
  );
}
